# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-Radio-V4L
version:      0.01
version_from: lib/Audio/Radio/V4L.pm
installdirs:  site
requires:
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
